// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqyqajbvhtgvjldebsxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeXFhamJ2aHRndmpsZGVic3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzM3NjIsImV4cCI6MjA3ODIwOTc2Mn0.ZkzEea-TZoEM9wvb1wtMqF0bP29w8PYN8kwMQXBiVFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});